snowflake_account = "MIB03883"
snowflake_user = "umairulla05"
snowflake_password = "Newboy@123"
snowflake_role = "ACCOUNTADMIN"
snowflake_warehouse = "medical_insight_analysis_wh"
snowflake_database = "medical_insight_analysis_db"
snowflake_schema = "PUBLIC"
